<?php
// $Id: ap_robotstxt.module,v 1.4.4.17 2009/02/21 08:59:51 hass Exp $

/**
 * Implementation of hook_help().
 */
function ap_robotstxt_help($path, $arg) {
  switch ($path) {
    case 'admin/help#ap_robotstxt':
      return '<p>'. t('In a multisite environment, there is no mechanism for having a separate robots.txt file for each site. This module addresses that need by letting you administer the robots.txt file from the settings interface.') .'</p>';
      break;

    case 'admin/settings/ap_robotstxt':
      if (file_exists('./robots.txt')) {
        drupal_set_message(t('One or more problems have been detected with the RobotsTxt configuration. Check the <a href="@status">status report</a> for more information.', array('@status' => url('admin/reports/status'))), 'warning');
      }
      return t('See <a href="http://www.robotstxt.org/">http://www.robotstxt.org/</a> for more information concerning how to write your <a href="@ap_robotstxt">robots.txt</a> file.', array('@ap_robotstxt' => base_path() . 'robots.txt'));
      break;
  }
}

/**
 * Implementation of hook_menu().
 */
function ap_robotstxt_menu() {
  
  $items['robots.txt'] = array(
    'page callback' => 'ap_robotstxt_robots',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/ap_robotstxt'] = array(
    'title' => 'ApRobotsTxt',
    'description' => "Manage Airplay Music's robots.txt file for to level domain: '" . ap_site_top_domain() . "'.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ap_robotstxt_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ap_robotstxt.admin.inc',
  );

  return $items;
}

/**
 * Show the robots.txt file.
 */
function ap_robotstxt_robots() {
    $content = array();
    $content[] = _ap_robotstxt_get_content();
    $content[] = _ap_robotstxt_get_content_site();

    // Hook other modules for adding additional lines.
//     if ($additions = module_invoke_all('ap_robotstxt')) {
//         $content = array_merge($content, $additions);
//     }

    // Trim any extra whitespace and filter out empty strings.
    $content = array_map('trim', $content);
    $content = array_filter($content);

    drupal_set_header('Content-type: text/plain');
    $robotstxt = implode("\n", $content);
    printf( "{$robotstxt}");
   // exit;
}

/**
Get  Airplay Music common contents of robots.txt from the database variable, site root, or
module directory. */
function _ap_robotstxt_get_content() {
  $content = variable_get('ap_robotstxt', FALSE);

  if ($content === FALSE) {
    $files = array(
      './robots.txt',
      drupal_get_path('module', 'ap_robotstxt') .'/ap_robots.txt',
    );
    foreach ($files as $file) {
      if (file_exists($file) && is_readable($file)) {
        $content = file_get_contents($file);
        break;
      }
    }
  }

  return $content;
}



/** Get Airplay Music domain specific contents of robots.txt file from Drupals variable table. */
function _ap_robotstxt_get_content_site($topDomain_s="") 
{
    if ( $topDomain_s == "" ) {
        $topDomain_s = ap_site_top_domain();
    }
    $var = "ap_robotstxt_{$topDomain_s}";
    
    $content = variable_get($var, "" );
    return $content;
}

// // function _ap_robotstxt_get_content_cur_site() 
// // {
// //     $topDomain_s = ap_site_top_domain();
// //     $var = "ap_robotstxt_{$topDomain_s}";
// //     $content = variable_get($var, "" );
// //     return $content;
// // }

