<div class="container footerfield_container">
<div class="span4 footertxt_left"><?php print render($page['footertxt_left']); ?></div>
<div class="span4 footertxt_center_left"><?php print render($page['footertxt_center_left']); ?></div>
<div class="span4 footertxt_center_right"><?php print render($page['footertxt_center_right']); ?></div>
<div class="span4 footertxt_right"><?php print render($page['footertxt_right']); ?><?php print ap_getFollowIcons(); ?></div>
</div>
