<?php 
// $Id$

module_load_include('inc', 'airplay_base', 'airplay_base_constants');  
module_load_include('inc', 'airplay_base', 'airplay_base_locale_functions');  
module_load_include('inc', 'airplay_base', 'airplay_base_url_functions');  
module_load_include('inc', 'airplay_admin', 'airplay_admin_db_views');  
module_load_include('inc', 'airplay_admin', 'airplay_admin_display_stats');  

function airplay_admin_all() {
// 	// --- Headline ---	
 	$sHeadLine = t('Airplay administration');
 	$page_content .= "<h2>$sHeadLine</h2>";
	return $page_content;
}


/**
* Implementation of hook_block
* @param string $op one of "list", "view", "save" and "configure"
* @param integer $delta code to identify the block
* @param array $edit only for "save" operation
**/
function airplay_admin_block($op = 'list', $delta = 0, $edit = array()) 
{ 
	if ($op == "list") {
		// Generate listing of blocks from this module, for the admin/block page
		$block = array();
		$block[0]["info"] = t('AirplayAdmin');
		return $block;
	  }
	else if ($op == 'view') {
		// Generate our block content
		
		//$sBlockContent = "<input id=airplay_admin_free_search ></input>";
		//$sBlockContent .= "<button >" . t("Seek airplay_admin") . "</button>";
		$sBlockContent = "<form action='/airplay_admin'>
		<input NAME='lookup' title='" . t('Search for') . "' /><BR />
		<input NAME='artist_name' title='" . t('Optional artist specification') . "' /><BR />
		<input type=submit value='" . t('Seek airplay_admin') . "' />
		<select name='search_for' >
			<option value=album >" . t('Album') . "</option>
			<option value=artist >" . t('Artist') . "</option>
			<option value=song >" . t('Song') . "</option>
		</select>
		</form>";
		
		// set up the block
		$block['subject'] = 'AirplayAdmin';
		$block['content'] = $sBlockContent;
		
		return $block;
	}
} // function airplay_admin_block

			
function airplay_admin_admin() 
{
	$form = array();
	
	$form['airplay_admin_maxdisp'] = array(
		'#type' => 'textfield',
		'#title' => t('Maximum number of links'),
		'#default_value' => variable_get('airplay_admin_maxdisp', 3),
		'#size' => 2,
		'#maxlength' => 2,
		'#description' => t("The maximum number of links to display in the block."),
		'#required' => TRUE,
	);
	
	return system_settings_form($form);
}

function airplay_admin_menu() 
{
	$items = array();
	
	$items['admin/settings/airplay_admin'] = array(
		'title' => 'AirplayAdmin module settings',
		'description' => 'Setup display settings for AirplayAdmin pages',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('airplay_admin_admin'),
		'access arguments' => array('access administration pages'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['airplay_admin'] = array(
		'title' => '',
		'page callback' => 'airplay_admin_main',
		'access arguments' => array('access airplay_admin content'),
		'type' => MENU_CALLBACK
	);
    $items['airplay_admin/display_latest_added'] = array(
        'title' => '',
        'page callback' => 'airplay_admin_display_latest_added',
        'access arguments' => array('access airplay_admin content'),
        'type' => MENU_CALLBACK
    );
    $items['airplay_admin/display_latest_upload'] = array(
        'title' => '',
        'page callback' => 'airplay_admin_display_latest_upload',
        'access arguments' => array('access airplay_admin content'),
        'type' => MENU_CALLBACK
    );


	return $items;
}

function airplay_admin_admin_validate($form, &$form_state) {
	$maxdisp = $form_state['values']['airplay_admin_maxdisp'];
	if (!is_numeric($maxdisp)) {
		form_set_error('airplay_admin_maxdisp', t('You must enter an integer for the maximum number of links.'));
	}
	else if ($maxdisp <= 0) {
		form_set_error('airplay_admin_maxdisp', t('Maximum number of links must be positive.'));
	}
}

/**
* Valid permissions for this module
* @return array An array of valid permissions for the airplay_admin module
*/
function airplay_admin_perm() {
	return array('access airplay_admin content');
} // function airplay_admin_perm()

function airplay_admin_permission() {
  return array(
    'access airplay_admin content' => array(
      'title' => t('Acces permissions for airplay_admin'),
    ),
  );
}


/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function airplay_admin_help($path, $arg) {
	$output = '';  //declare your output variable
	switch ($path) {
		case "admin/help#airplay_admin":
		$output = '<p>'.  t("Displays the airplay_admin page in AirplayMusic Drupal CMS") .'</p>';
		break;
	}
	return $output;
} // function airplay_admin_help



